### ISSUE TITLE
get_bgp_config: Waiting for 2 arguments while meta-data shows only 1 mandatory

### ISSUE THREAD

**Issue by mab27** [StackStorm-Exchange/stackstorm-napalm#15] opened 2017-04-24 16:31 UTC
```
mab@mab-infra:/opt/stackstorm/packs/napalm$ sudo st2 run napalm.get_bgp_config hostname=vmx1
.
id: 58fe1c707cae220853c42553
status: failed
parameters: 
  hostname: vmx1
result: 
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 259, in <module>
    obj.run()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 155, in run
    output = action.run(**self._parameters)
TypeError: run() takes exactly 3 arguments (2 given)
"
  stdout: ''
```

Looks like the action is expecting 2 argumets while the meta-data shows only 1 being mandatory.

```
mab@mab-infra:/opt/stackstorm/packs/napalm$ sudo st2 run napalm.get_bgp_config hostname=vmx1 -h

Get BGP configuration from a device using NAPALM.

Required Parameters:
    hostname
        The hostname of the device to connect to. Driver must be specified if
        hostname is not in configuration. Hostname without FQDN can be given
        if device is in configuration.
        Type: string

Optional Parameters:
    driver
        Device driver name for connecting to device, see
        https://napalm.readthedocs.io/en/latest/support/index.html for list.
        Type: string

    port
        port for accessing device
        Type: string

    credentials
        The credentials group which contains the username and password to log
        in
        Type: string

    group
        Restrict configuration to this BGP neighbor/Peer group
        Type: string

    neighbor
        Restrict configuration to this BGP neighbor
        Type: string

    htmlout
        In addition to the normal output also includes html output.
        Type: boolean

    env
        Environment variables which will be available to the script.
        Type: object

    timeout
        Action timeout in seconds. Action will get killed if it doesn't finish
        in timeout seconds.
        Type: integer
        Default: 600
```

**Comment by Mierdin** [comment] 2017-04-27 16:38
This was caused by the metadata referencing the "neighbor" parameter, yet the underlying Python script expected "neighbour". This resulted in the "neighbor" parameter going to `**kw_args`, and `neighbour` remaining unset.

Will be fixed in #17

**Closed as completed** 2017-05-03 21:59 UTC
